### ISSUE TITLE
Query with CGAT/blat

### ISSUE THREAD

**Issue by mpevs** [willblev/fasta-to-gtf#1]
I'm trying to run fasta-to-gtf but get error messages because blat is not installed. I was wondering how to download and install CGAT and/or blat so that it works with this program? Apologies for flagging this as an issue - it's no problem with the program, just me!

**Comment by willblev** [comment]
Hi mpevs, 

You can download BLAT (version 34) directly from [this link](https://users.soe.ucsc.edu/~kent/src/blatSrc34.zip). If you want to install the CGAT collection of tools, you can find the instructions on their [GitHub page](https://github.com/CGATOxford/cgat). Hope this helps!
